site_name: Lambda文档
repo_url: https://github.com/LambdaIM/launch
repo_name: GitHub
edit_uri: blob/master/
site_description: Lambda文档
site_author: Lambda Team
nav:
    - 首页: index.md
    - 使用必知: must-known-cn.md
    - 应用开发指导: Application-Develop-Guide.md
    - 主网接入:
          - 验证节点接入: Mainnet-Validator-Guide.md
          - 矿工接入: Mainnet-Miner-Guide.md
          - 0.3.3节点升级: Mainnet-Validator-Upgrade-Guide.md
          - 验证节点迁移: Lambda-Validator-Migration.md
          - 主网接入帮助: FAQ.md
          - 主网稳定版本: version/MainnetStable.md
          - 主网最新版本: version/MainnetLatest.md
    - 测试网接入:
          - 验证节点接入: Testnet-Validator-Guide.md
          - 矿工接入: Testnet-Miner-Guide.md
          - 存储节点接入: Testnet-Storagenode-Configure.md
          #- 0.4.8节点升级: Testnet-Validator-Upgrade-Guide.md
          #- Storage0.2.5升级: Lambda-Store-Upgrade.md
          - 同步节点: Testnet-Sync-Node.md
          - 验证节点挖矿手册: Lambda-Validator-Mining.md
          - 存储矿工挖矿手册: Lambda-Store-and-Mining.md
          - 存储网络文件备份和恢复: StorageFile-Backup.md
          - 测试网最新版本: version/TestnetLatest.md
    - 钱包:
          - 桌面钱包使用手册: Lambda-Wallet-Guide.md
          - 桌面钱包稳定版本: version/WalletStable.md
          - 桌面钱包最新版本: version/WalletLatest.md
          - 手机钱包稳定版本: version/MobileWalletStable.md
          - 手机钱包最新版本: version/MobileWalletLatest.md
    - 矿工管理程序:
          - 使用手册: StorageManager-Guide.md
          - 稳定版本: version/StorageManagerStable.md
          - 最新版本: version/StorageManagerLatest.md
    - API文档:
          - 钱包API接入文档: Wallet-API.md
          - S3Gateway API文档: S3-Gateway-API.md
          - 区块链API文档: api-reference/paths.md
#          - 浏览器API文档: http://59.110.68.178:8081/swagger/
    - 使用文档:
        - 质押操作手册: Delegate-Operation-Guide.md
        - 资产管理: Asset-Manage-Guide.md
        - 社区治理: governance.md
        - 命令行使用:
            - lambdacli:
                - lambdacli: lambdacli/README.md
                - status: lambdacli/status/README.md
                - query: lambdacli/query/README.md
                - tx: lambdacli/tx/README.md
                - keys: lambdacli/keys/README.md
                - version: lambdacli/version/README.md
            - minernode: minernode/README.md
            - storagenode: storagenode/README.md
            - storagecli: storagecli/README.md
    - 浏览器:
        - 主网浏览器: http://explorer.lambda.im/#/
        - 测试网浏览器: http://testbrowser.lambda.im/#/
theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: red
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed
